CREATE TABLE IF NOT EXISTS FACTS (
  ID       IDENTITY PRIMARY KEY,
  USER     VARCHAR(50),
  DATE     DATE,
  ACCOUNT  VARCHAR(50),
  CATEGORY  VARCHAR(50),
  AMOUNT   NUMBER(18, 2),
  COMMENT  VARCHAR(100),
  SUBTOTAL NUMBER(18, 2),
  MONTH    VARCHAR(50)
);

